package com.devInnovators.Whatchdog.Query.domain.model;

public enum QueryCategoryIssue {
    INFRAESTRUCTURA_VIAL,
    ILUMINACION_PUBLICA,
    GESTION_RESIDUOS,
    ESPACIOS_VERDES,
    TRANSPORTE_PUBLICO,
    AGUA_Y_DRENAJE,
    SEGURIDAD_CIUDADANA,
    CONTAMINACION,
    SERVICIOS_PUBLICOS,
    EDIFICACIONES_Y_OBRAS,
    MOVILIDAD_Y_ACCESIBILIDAD,
    ANIMALES,
    INSEGURIDAD_VIAL,
    MOBILIARIO_URBANO;
}
