FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY target/WatchdogRevisionPriorizacion-0.0.1-SNAPSHOT.jar /app/WatchdogRevisionPriorizacion.jar

EXPOSE 8081

ENTRYPOINT [ "java", "-jar", "WatchdogRevisionPriorizacion.jar" ]


